"""Add username, full_name, company to User model

Revision ID: 00b2be4693ed
Revises:
Create Date: 2025-10-14 10:16:05.957786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b2be4693ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Create tenant if missing
    if not inspector.has_table('tenant'):
        op.create_table('tenant',
            sa.Column('id', sa.INTEGER(), nullable=False),
            sa.Column('name', sa.VARCHAR(), nullable=False),
            sa.Column('domain', sa.VARCHAR(), nullable=False),
            sa.Column('is_active', sa.BOOLEAN(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('domain')
        )
    # create index if not exists
    existing = [idx['name'] for idx in inspector.get_indexes('tenant')] if inspector.has_table('tenant') else []
    if 'ix_tenant_id' not in existing:
        op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)

    # Create user if missing
    if not inspector.has_table('user'):
        op.create_table('user',
            sa.Column('id', sa.INTEGER(), nullable=False),
            sa.Column('email', sa.VARCHAR(), nullable=False),
            sa.Column('username', sa.VARCHAR(), nullable=True),
            sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
            sa.Column('full_name', sa.VARCHAR(), nullable=True),
            sa.Column('company', sa.VARCHAR(), nullable=True),
            sa.Column('is_active', sa.BOOLEAN(), nullable=True),
            sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
            sa.Column('tenant_id', sa.INTEGER(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    existing_user_idx = [idx['name'] for idx in inspector.get_indexes('user')] if inspector.has_table('user') else []
    if 'ix_user_email' not in existing_user_idx:
        op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    if 'ix_user_id' not in existing_user_idx:
        op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    if 'ix_user_username' not in existing_user_idx:
        op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=1)

    # Create email if missing
    if not inspector.has_table('email'):
        op.create_table('email',
            sa.Column('id', sa.INTEGER(), nullable=False),
            sa.Column('subject', sa.VARCHAR(), nullable=False),
            sa.Column('body', sa.TEXT(), nullable=False),
            sa.Column('recipient_email', sa.VARCHAR(), nullable=False),
            sa.Column('sender_email', sa.VARCHAR(), nullable=False),
            sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
            sa.Column('status', sa.VARCHAR(), nullable=True),
            sa.Column('tenant_id', sa.INTEGER(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    existing_email_idx = [idx['name'] for idx in inspector.get_indexes('email')] if inspector.has_table('email') else []
    if 'ix_email_id' not in existing_email_idx:
        # create index on id
        op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
