"""add sends and usersubscription and invoice fields

Revision ID: 7f282a4e2d7d
Revises: a9aa945befa5
Create Date: 2025-10-29 14:06:22.119634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f282a4e2d7d'
down_revision: Union[str, Sequence[str], None] = 'a9aa945befa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('send', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('send', sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('send', 'invoice_date')
    op.drop_column('send', 'invoice_number')
    # ### end Alembic commands ###
