"""add sends and user_subscription

Revision ID: a9aa945befa5
Revises: 20251029_addprf
Create Date: 2025-10-29 13:27:21.972024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9aa945befa5'
down_revision: Union[str, Sequence[str], None] = '20251029_addprf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricingplan.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscriptionplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersubscription_id'), 'usersubscription', ['id'], unique=False)
    op.create_table('send',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_subscription_id', sa.Integer(), nullable=True),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=True),
    sa.Column('nb_bulletins', sa.Integer(), nullable=False),
    sa.Column('price_per_bulletin', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('invoice_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricingplan.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['usersubscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_id'), 'send', ['id'], unique=False)
    op.alter_column('email', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email', 'recipient_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email', 'sender_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('email', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('email_tenant_id_fkey'), 'email', type_='foreignkey')
    op.create_foreign_key(None, 'email', 'tenant', ['tenant_id'], ['id'])
    op.alter_column('pricingplan', 'subscription_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tenant', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tenant', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tenant', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # Handle tenant_domain_key which may be an index or a unique constraint.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    uniq_names = [c['name'] for c in inspector.get_unique_constraints('tenant')] if inspector.has_table('tenant') else []
    idx_names = [i['name'] for i in inspector.get_indexes('tenant')] if inspector.has_table('tenant') else []
    if 'tenant_domain_key' in uniq_names:
        op.drop_constraint('tenant_domain_key', 'tenant', type_='unique')
    elif 'tenant_domain_key' in idx_names:
        op.drop_index(op.f('tenant_domain_key'), table_name='tenant')
    # create ix_tenant_id if missing
    existing_idx = [i['name'] for i in inspector.get_indexes('tenant')] if inspector.has_table('tenant') else []
    if 'ix_tenant_id' not in existing_idx:
        op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    # create unique constraint on domain if missing
    existing_uniques = [c['name'] for c in inspector.get_unique_constraints('tenant')] if inspector.has_table('tenant') else []
    if 'tenant_domain_key' not in existing_uniques:
        op.create_unique_constraint(None, 'tenant', ['domain'])
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # user email/username uniqueness may be implemented as a unique constraint
    # or as an index depending on how earlier migrations were applied.
    user_uniques = [c['name'] for c in inspector.get_unique_constraints('user')] if inspector.has_table('user') else []
    user_indexes = [i['name'] for i in inspector.get_indexes('user')] if inspector.has_table('user') else []
    if 'user_email_key' in user_uniques:
        op.drop_constraint('user_email_key', 'user', type_='unique')
    elif 'user_email_key' in user_indexes:
        op.drop_index(op.f('user_email_key'), table_name='user')
    if 'user_username_key' in user_uniques:
        op.drop_constraint('user_username_key', 'user', type_='unique')
    elif 'user_username_key' in user_indexes:
        op.drop_index(op.f('user_username_key'), table_name='user')
    # create user indexes only if they don't already exist
    existing_user_idx = [i['name'] for i in inspector.get_indexes('user')] if inspector.has_table('user') else []
    if 'ix_user_email' not in existing_user_idx:
        op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    if 'ix_user_id' not in existing_user_idx:
        op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    if 'ix_user_username' not in existing_user_idx:
        op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # Drop existing foreign key from user. Some DBs may have a differently
    # named FK or none at all, so check first.
    user_fks = [fk['name'] for fk in inspector.get_foreign_keys('user')] if inspector.has_table('user') else []
    if 'user_tenant_id_fkey' in user_fks:
        op.drop_constraint(op.f('user_tenant_id_fkey'), 'user', type_='foreignkey')
    # create FK if missing
    if 'user_tenant_id_fkey' not in user_fks:
        op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_tenant_id_fkey'), 'user', 'tenant', ['tenant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('user_username_key'), 'user', ['username'], unique=True)
    op.create_index(op.f('user_email_key'), 'user', ['email'], unique=True)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.create_index(op.f('tenant_domain_key'), 'tenant', ['domain'], unique=True)
    op.alter_column('tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenant', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tenant', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('pricingplan', 'subscription_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('email', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.create_foreign_key(op.f('email_tenant_id_fkey'), 'email', 'tenant', ['tenant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.alter_column('email', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('email', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('email', 'sender_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email', 'recipient_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('email', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_send_id'), table_name='send')
    op.drop_table('send')
    op.drop_index(op.f('ix_usersubscription_id'), table_name='usersubscription')
    op.drop_table('usersubscription')
    # ### end Alembic commands ###
